mysite/urls.py
"""mysite URL Configuration
"""

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('quest.urls')),
    url(r'^squrl/', include('squrl.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quest/urls.py
from django.conf.urls import url

from . import views

app_name = 'quest'
urlpatterns = [
    url(r'^$', views.get_urlbuilder, name='index'),
    url(r'^(?P<source_id>.+)/results/$', views.get_results, name='results'),
    url(r'^analysis/$', views.get_analysis, name='analysis'),
    url(r'^mail/$', views.get_mail, name='mail'),
    url(r'^contact/$', views.get_contact, name='contact'),
    url(r'^projects/$', views.get_projects, name='projects'),
    url(r'^404/$', views.get_404, name='404'),
]

squrl/urls.py
from django.conf.urls import url

from . import views

app_name = 'squrl'
urlpatterns = [
    url(r'^$', views.get_squrl, name='squrl'),
    url(r'^shorten_url$', views.get_json, name='shorten_url'),
    url(r'^(?P<short_url>\w{8})$', views.redirect_url, name='redirect'),
]

quest/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    """
    Model for questions with pub date
    """
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        """
        Checks if question was published recently
        """
        now = timezone.now()
        # check if a question was posted within a day from today
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    """
    Model for choices linked to Questions via a foreign key
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

quest/forms.py
from django import forms
from django.conf import settings


class URLBuilderForm(forms.Form):
    """
    The form on Index page taking inputs to build source url
    """
    q1 = forms.ChoiceField(
        label="Which country are you interested in?",
        widget=forms.RadioSelect,
        choices=settings.CHOICES_Q1)
    q2 = forms.ChoiceField(
        label="Which language are you interested in?",
        widget=forms.RadioSelect,
        choices=settings.CHOICES_Q2)
    q3 = forms.ChoiceField(
        label="Which category of news articles are you interested in?",
        widget=forms.RadioSelect,
        choices=settings.CHOICES_Q3)


class ArticleForm(forms.Form):
    """
    The form on the Results page taking the article id to build url
    """
    article_id = forms.IntegerField(label="Article ID ", initial=0)
    url_list = forms.CharField(widget=forms.HiddenInput())


class EmailForm(forms.Form):
    """
    The form taking email ID as input to send article information
    """
    subject = forms.CharField(widget=forms.HiddenInput())
    email = forms.EmailField(label='E-mail ID ')
    message = forms.CharField(widget=forms.HiddenInput())


class ContactForm(forms.Form):
    """
    Contact form for Contact page
    """
    your_name = forms.CharField(label='Your Name ', max_length=100)
    sender = forms.EmailField(label='Your E-mail ')
    message = forms.CharField(label='Your Message ')

quest/views.py
import ast
import json
import pandas
import newspaper

from django.urls import reverse
from django.shortcuts import render
from django.core.mail import send_mail
from django.http import HttpResponseRedirect

from urllib.request import urlopen
from textblob import TextBlob

from .forms import ContactForm, URLBuilderForm, ArticleForm, EmailForm


def get_urlbuilder(request):
    """
    This view method gets called on name url index
    If GET, URLBuilderForm is rendered on index.html
    If POST, building_source_url method is called and list of sources rendered on sources.html
    """
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request
        form = URLBuilderForm(request.POST)
        # check whether it is valid
        if form.is_valid():

            q1 = form.cleaned_data['q1']
            q2 = form.cleaned_data['q2']
            q3 = form.cleaned_data['q3']

            # if q1, q2 or q3 set to all, make them empty
            if q1 == 'all':
                q1 = ''
            if q2 == 'all':
                q2 = ''
            if q3 == 'all':
                q3 = ''

            # build url accrding to params selected
            sources = building_source_url(q1, q2, q3)

            # if no sources returned with selected parameters, render index.html with error
            if len(sources['sources']) < 1:
                # return render(
                #     request,
                #     'quest/index.html',
                #     {
                #         'form': form,
                #         'error': "*Your inputs resulted in 0 news sources. Please try again with different inputs.",
                #         'trending_searches': " | ".join(
                #             newspaper.hot())})
                sources = building_source_url("", "", "")
                return render(request,
                              'quest/sources.html',
                              {'sources': sources,
                               'error': "*Your inputs resulted in 0 news sources. Showing all possible sources.",
                               'trending_searches': " | ".join(newspaper.hot())})

            # on success of getting list of sources, render sources.html with source data
            else:
                return render(request,
                              'quest/sources.html',
                              {'sources': sources,
                               'trending_searches': " | ".join(newspaper.hot())})

    # if a GET (or any other method) we'll create a blank form
    else:
        form = URLBuilderForm()
        return render(request,
                      'quest/index.html',
                      {'form': form,
                       'trending_searches': " | ".join(newspaper.hot())})


def building_source_url(q1, q2, q3):
    # initializing variables
    # newsAPI key
    api_key = "e85d175055ae4a8a81e45640560b8e37"
    # newsAPI base url structure for getting sources
    sources_url = "https://newsapi.org/v1/sources?apiKey=" + api_key

    # append params to base url to get sources from newsAPI
    final_url = sources_url + "&country=" + \
        q1 + "&language=" + q2 + "&category=" + q3

    # return json of list of news sources
    return json.loads(urlopen(final_url).read())


def get_results(request, source_id):
    """
    This view method gets called when source link is clicked on sources.html with name url results
    ArticleForm is rendered on results.html with url_list as a hidden parameter
    """
    # initializing variables
    # newsAPI key
    api_key = "e85d175055ae4a8a81e45640560b8e37"
    # newsAPI base url structure for getting articles
    articles_url = "https://newsapi.org/v1/articles?apiKey=" + api_key

    # append params to base url to get articles from the given source
    final_url = articles_url + "&source=" + source_id
    temp_var = json.loads(urlopen(final_url).read())['articles']

    # making a list of article urls
    url_list = [v['url'] for v in temp_var]

    # create a dataframe of teh article data
    articles_df = pandas.DataFrame(temp_var)

    # ensuring display of complete contents in table cells
    pandas.set_option('display.max_rows', 1000)
    pandas.set_option('display.max_colwidth', 1000)

    # initialize the Article form with the url_list passed as a hidden field
    form = ArticleForm(
        initial={"url_list": url_list})
    return render(request,
                  'quest/results.html',
                  {'articles': articles_df.to_html(),
                   'form': form,
                   'url_list': url_list,
                   'trending_searches': " | ".join(newspaper.hot())})


def get_analysis(request):
    """
      This view method gets called on name url analysis
      If GET, list of all available sources is rendered on sources.html with blank form for emailing
      If POST, article info is extracted, analysed and rendered on analysis.html
    """
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ArticleForm(request.POST)

        # check whether it's valid:
        if form.is_valid():
            article_id = form.cleaned_data['article_id']

            # if article id is negative, default to 0
            if article_id < 0:
                article_id = 0

            # convert the string representation of the list to list datatype
            url_list = ast.literal_eval(form.cleaned_data['url_list'])

            # get the article url from the list using article id
            article_url = url_list[article_id]

            # get the article details using newspaper library
            a = newspaper.Article(article_url)

            a.build()

            a_dict = {'url': article_url,
                      'img': a.top_image,
                      'authors': " | ".join(a.authors),
                      'title': a.title,
                      'desc': a.text,
                      'keywords': " | ".join(a.keywords),
                      'summary': a.summary,
                      'polarity': str(TextBlob(a.text).sentiment.polarity)}

            # initializing the email form with article title as subject and message containing article details
            emailform = EmailForm(
                initial={
                    'subject': a_dict['title'],
                    'message': "\n".join(
                        [
                            "Keywords: ",
                            a_dict['keywords'],
                            "Summary: ",
                            a_dict['summary'],
                            "Polarity: ",
                            a_dict['polarity'],
                            "Description: ",
                            a_dict['desc']])})

            return render(request,
                          'quest/analysis.html',
                          {'form': emailform,
                           'a_dict': a_dict,
                           'trending_searches': " | ".join(newspaper.hot())})

    # if a GET (or any other method) we'll render sources.html with complete source list
    else:
        sources = building_source_url("", "", "")
        return render(request,
                      'quest/sources.html',
                      {'sources': sources,
                       'trending_searches': " | ".join(newspaper.hot())})


def get_mail(request):
    """
    This view method gets called when send mail link is clicked on analysis.html with name url mail
    If GET, list of all available sources is rendered on sources.html with blank form for emailing
    If POST, article info is extracted, email is sent with article details and analysis
    """
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request
        form = EmailForm(request.POST)
        # check whether it's valid
        if form.is_valid():
            subject = form.cleaned_data['subject']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            sender = 'ishijain89@gmail.com'
            recipients = ['ijain89@gmail.com', email]

            send_mail(subject, message, sender, recipients)

            # redirect to contact page after mail sent
            return HttpResponseRedirect(reverse('quest:contact'))

    # if a GET (or any other method) we'll render sources.html with complete source list
    else:
        sources = building_source_url("", "", "")
        return render(request,
                      'quest/sources.html',
                      {'sources': sources,
                       'trending_searches': " | ".join(newspaper.hot())})


def get_contact(request):
    """
    This view method gets called on name url contact
    If GET, ContactForm rendered blank for emailing
    If POST, email is sent and page redirected to home page
    """
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request
        form = ContactForm(request.POST)
        # check whether it's valid
        if form.is_valid():
            your_name = form.cleaned_data['your_name']
            sender = form.cleaned_data['sender']
            message = form.cleaned_data['message']

            recipients = ['ijain89@gmail.com']

            send_mail(your_name, " | ".join(
                [sender, message]), sender, recipients)
            # redirect to index page after mail sent
            return HttpResponseRedirect(reverse('quest:index'))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ContactForm()
        return render(request,

quest/templates/quest/base.html
{% load static %}

<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, maximum-scale=1">
<title>IshitaJain</title>

<link rel="icon" href="{% static 'quest/favicon.png' %}" type="image/png">
<link href="{% static 'quest/css/bootstrap.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'quest/css/style.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'quest/css/linecons.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'quest/css/font-awesome.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'quest/css/responsive.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'quest/css/animate.css' %}" rel="stylesheet" type="text/css">

<link href='http://fonts.googleapis.com/css?family=Lato:400,900,700,700italic,400italic,300italic,300,100italic,100,900italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Dosis:400,500,700,800,600,300,200' rel='stylesheet' type='text/css'>

<!--[if IE]><style type="text/css">.pie {behavior:url(PIE.htc);}</style><![endif]-->

<script type="text/javascript" src="{% static 'quest/js/jquery.1.8.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'quest/js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'quest/js/jquery-scrolltofixed.js' %}"></script>
<script type="text/javascript" src="{% static 'quest/js/jquery.easing.1.3.js' %}"></script>
<script type="text/javascript" src="{% static 'quest/js/jquery.isotope.js' %}"></script>
<script type="text/javascript" src="{% static 'quest/js/wow.js' %}"></script>
<script type="text/javascript" src="{% static 'quest/js/classie.js' %}"></script>

<!--[if lt IE 9]>
    <script src="{% static 'quest/js/respond-1.1.0.min.js' %}"></script>
    <script src="{% static 'quest/js/html5shiv.js' %}"></script>
    <script src="{% static 'quest/js/html5element.js' %}"></script>
<![endif]-->

<script type="text/javascript">
	$(document).ready(function(e) {
        $('.res-nav_click').click(function(){
		$('ul.toggle').slideToggle(600)
			});

	$(document).ready(function() {
$(window).bind('scroll', function() {
         if ($(window).scrollTop() > 0) {
             $('#header_outer').addClass('fixed');
         }
         else {
             $('#header_outer').removeClass('fixed');
         }
    });

	  });


		    });
function resizeText() {
	var preferredWidth = 767;
	var displayWidth = window.innerWidth;
	var percentage = displayWidth / preferredWidth;
	var fontsizetitle = 25;
	var newFontSizeTitle = Math.floor(fontsizetitle * percentage);
	$(".divclass").css("font-size", newFontSizeTitle)
}
</script>
</head>
<body>

<!--Header_section-->
<header id="header_outer">
  <div class="container">
    <div class="header_section">
      <div class="logo"><a href="{% url 'quest:index' %}"><img src="{% static 'quest/img/logo.png' %}" alt=""></a></div>
      <nav class="nav" id="nav">
        <ul class="toggle">
          <li><a href="{% url 'squrl:squrl' %}">Try sqURL</a></li>
          <li><a href="{% url 'quest:index' %}">Try newsQuest</a></li>
          <li><a href="{% url 'quest:projects' %}">Other Projects</a></li>
          <li><a href="{% url 'quest:contact' %}">About me</a></li>
        </ul>
        <ul class="">
          <li><a href="{% url 'squrl:squrl' %}">Try sqURL</a></li>
          <li><a href="{% url 'quest:index' %}">Try newsQuest</a></li>
          <li><a href="{% url 'quest:projects' %}">Other Projects</a></li>
          <li><a href="{% url 'quest:contact' %}">About me</a></li>
        </ul>
      </nav>
      <a class="res-nav_click animated wobble wow"  href="javascript:void(0)"><i class="fa-bars"></i></a>
    </div>
  </div>
</header>
<!--Header_section-->
{% block content %}
{% endblock content %}
<!--Service-->
<section class="twitter-feed"><!--twitter-feed-->
  <div class="container  animated fadeInDown delay-07s wow">
    <h4><span>Trending searches on Google!</span></h4>
    <p>{{ trending_searches }}</p>
  </div>
</section>

<footer class="footer_section" id="contact">
  <div class="container">
    <div class="footer_bottom"> <span>Copyright © 2017 <a href="{% url 'quest:contact' %}">Ishita Jain</a></span> </div>
  </div>
</footer>

<script type="text/javascript">
    $(document).ready(function(e) {
        $('#header_outer').scrollToFixed();
        $('.res-nav_click').click(function(){
            $('.main-nav').slideToggle();
            return false

        });

    });
</script>
<script type="text/javascript">
	$(window).load(function(){

		$('a').bind('click',function(event){
			var $anchor = $(this);

			$('html, body').stop().animate({
				scrollTop: $($anchor.attr('href')).offset().top - 91
			}, 1500,'easeInOutExpo');
			/*
			if you don't want to use the easing effects:
			$('html, body').stop().animate({
				scrollTop: $($anchor.attr('href')).offset().top
			}, 1000);
			*/
			event.preventDefault();
		});
	})
</script>

<script type="text/javascript">


  jQuery(document).ready(function($){
// Portfolio Isotope
	var container = $('#portfolio-wrap');


	container.isotope({
		animationEngine : 'best-available',
	  	animationOptions: {
	     	duration: 200,
	     	queue: false
	   	},
		layoutMode: 'fitRows'
	});

	$('#filters a').click(function(){
		$('#filters a').removeClass('active');
		$(this).addClass('active');
		var selector = $(this).attr('data-filter');
	  	container.isotope({ filter: selector });
        setProjects();
	  	return false;
	});


		function splitColumns() {
			var winWidth = $(window).width(),
				columnNumb = 1;


			if (winWidth > 1024) {
				columnNumb = 8;
			} else if (winWidth > 900) {
				columnNumb = 6;
			} else if (winWidth > 479) {
				columnNumb = 3;
			} else if (winWidth < 479) {
				columnNumb = 1;
			}

			return columnNumb;
		}

		function setColumns() {
			var winWidth = $(window).width(),
				columnNumb = splitColumns(),
				postWidth = Math.floor(winWidth / columnNumb);

			container.find('.portfolio-item').each(function () {
				$(this).css( {
					width : postWidth + 'px'
				});
			});
		}

		function setProjects() {
			setColumns();
			container.isotope('reLayout');
		}

		container.imagesLoaded(function () {
			setColumns();
		});


		$(window).bind('resize', function () {
			setProjects();
		});

});
$( window ).load(function() {
	jQuery('#all').click();
	return false;
});
</script>
</body>
</html>

quest/templates/quest/contact.html
{% extends "quest/base.html" %}
{% load static %}

{% block content %}
<section class="main-section team" id="team"><!--main-section team-start-->
  <div class="container">
    <h2>Hi! I'm Ishita Jain.</h2>
    <h6>I'm an agile Parselmouth (read: "Python" is my language and I believe in agile methodology) having strong analytical skills and an interest in automating systems. I was a core member for development of a new, lighter and faster website for Dubizzle.com's e-commerce expansion from Dubai to Middle East North Africa; reduced page load time from 2.29 to 0.8 seconds. Currently working as Platform Lead of Software &amp; Training Unit at JLJ Group, India, I take ownership of successful project on-boarding, implementation (by teams of 4-6 while doubling up as a code contributor myself) and delivery. With 4 years of experience in working effectively within teams as well as against deadlines, I am a seasoned self-motivated team player. I have a bachelor's degree in Computer Science Engineering with honors in Data Analytics &amp; Warehousing, Image Analysis &amp; Machine Intelligence and Finance streams. I received the University's All Rounder Gold Medal for consistent academic and overall performance. With an undying passion for exploring new experiences, I have visited 16 countries across 4 continents and counting.</h6>
    <div class="team-leader-block clearfix">
      <div class="team-leader-box">
        <div class="team-leader wow fadeInDown delay-03s">
          <div class="team-leader-shadow"></div>
          <img src="{% static 'quest/img/IshitaJain.jpg'  %}" alt="">
        </div>
        <h3 class="wow fadeInDown delay-03s">POSITIONS OF RESPONSIBILITY </h3>
        <span class="wow fadeInDown delay-03s">IIIT Delhi</span>
        <p class="wow fadeInDown delay-03s">
          <ul>
            <li>
              <div class="row" style="text-align:left;">
                <div class="col-lg-3">
                  <b>Senate Member</b>
                </div>
                <div class="col-lg-9">
                  Voted as the IIITD Student Council Representative twice (2008 – 10, 2011 – 12)
                </div>
              </div>
            </li>
            <li>
              <div class="row" style="text-align:left;">
                <div class="col-lg-3">
                  <b>Cultural Coordinator, IIITD</b>
                </div>
                <div class="col-lg-9">
                  Founded Music Club; Introduced intra-college music competitions (2008 – 10)
                </div>
              </div>
            </li>
            <li>
              <div class="row" style="text-align:left;">
                <div class="col-lg-3">
                  <b>Treasurer Office Bearer</b>
                </div>
                <div class="col-lg-9">
                   IIITD-ACM Student Chapter - Budgeting and operations for the fiscal year (2010 – 11)
                </div>
              </div>
            </li>          
            <li>
              <div class="row" style="text-align:left;">
                <div class="col-lg-3">
                  <b>Organizing Team</b>
                </div>
                <div class="col-lg-9">
                  First Techfest of IIITD – ESYA (2012)
                </div>
              </div>
            </li>          
            <li>
              <div class="row" style="text-align:left;">
                <div class="col-lg-3">
                  <b>Founder</b>
                </div>
                <div class="col-lg-9">
                  Pixelate IIITD-ACM Photography Interest Group
                </div>
              </div>
            </li>
          </ul>
        </p>      
      </br><h3 class="wow fadeInDown delay-03s">EXTRA-CURRICULAR ACTIVITIES</h3></br>
        <p class="wow fadeInDown delay-03s">
          <ul>
            <li>
              <div class="row" style="text-align:left;">
                <div class="col-lg-3">
                  <b>Music</b>
                </div>
                <div class="col-lg-9">
                  4 year Diploma, Classical Vocal; Won State Level; represented at Nationals (SangamKala, Sangeetayan)
                </div>
              </div>
            </li>          
            <li>
              <div class="row" style="text-align:left;">
                <div class="col-lg-3">
                  <b>Arts</b>
                </div>
                <div class="col-lg-9">
                  Received prizes at the National Shankar’s Art Competition for 4 years (1997 – 2000); Silver Medal in 2001
                </div>
              </div>
            </li>          
            <li>
              <div class="row" style="text-align:left;">
                <div class="col-lg-3">
                  <b>Social</b>
                </div>
                <div class="col-lg-9">
                  Women Empowerment: organized Azaad Naari Workshop; Speaker at Panel Discussions</br>Isha Foundation, Volunteer – non-profit promotes Yoga, social upliftment and ecological conservation</br>Kanya Ashram, Facilitator – home-school for orphaned girls; Facilitated donation of 1000 clothes till date</br>Taught under-privileged kids for 2 years in an NGO, Anubhav Shiksha Kendra at RK Puram, Delhi
                </div>
              </div>
            </li>          
            <li>
              <div class="row" style="text-align:left;">
                <div class="col-lg-3">
                  <b>Sports</b>
                </div>
                <div class="col-lg-9">
                  Won medal in the 5Km Dubai Women’s Run at the Palm (2012)</br>Won the Intra-College Women Football Tournament and Golden Boot award twice, Women Table Tennis Tournament twice and earned third position in Billiards Tournament
                </div>
              </div>
            </li>          
            <li>
              <div class="row" style="text-align:left;">
                <div class="col-lg-3">
                  <b>Travel</b>
                </div>
                <div class="col-lg-9">
                  Avid traveler: Visited 16 countries across 4 continents
                </div>
              </div>
            </li>
          </ul>
        </p>  
      </div>
    </div>
  </div>
</section>
<!--Header_section-->
<footer class="footer_section" id="contact">
  <div class="container">
    <section class="main-section contact" id="contact">
      <div class="contact_section">
        <h2>Contact</h2>
        <div class="row">
          <div class="col-lg-4">
            <div class="contact_block">
              <div class="contact_block_icon rollIn animated wow"><span><i class="fa-home"></i></span></div>
              <span> New Delhi, India </span> </div>
          </div>
          <div class="col-lg-4">
            <div class="contact_block">
              <div class="contact_block_icon icon2 rollIn animated wow"><span><i class="fa-phone"></i></span></div>
              <span> +91-9899732100 </span> </div>
          </div>
          <div class="col-lg-4">
            <div class="contact_block">
              <div class="contact_block_icon icon3 rollIn animated wow"><span><i class="fa-pencil"></i></span></div>
              <span> <a href="mailto:ijain89@gmail.com "> ijain89@gmail.com </a> </span> </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-6 wow fadeInLeft">
          <div class="contact-info-box address clearfix">
            <h3>Fill the form and I'll contact you soon!</h3>
            <p>Watch this page for further development of Project Newsquest. Feedback and suggestions are welcomed!</p>
          </div>
          <ul class="social-link">
            <li class="facebook animated bounceIn wow delay-02s"><a href="https://www.facebook.com/ijain89"><i class="fa-facebook"></i></a></li>
            <li class="gplus animated bounceIn wow delay-03s"><a href="https://plus.google.com/+IshitaJain89"><i class="fa-google-plus"></i></a></li>
            <li class="bitbucket animated bounceIn wow delay-04s"><a href="https://bitbucket.org/JLJ/"><i class="fa-bitbucket"></i></a></li>
          </ul>
        </div>
        <div class="col-lg-6 wow fadeInUp delay-06s">
          <div class="form">
            <form action="{% url 'quest:contact' %}" method="post">
                {% csrf_token %}
                <input class="input-text animated wow flipInY delay-02s" id="id_your_name" type="text" name="your_name" value="Your Name *" onFocus="if(this.value==this.defaultValue)this.value='';" onBlur="if(this.value=='')this.value=this.defaultValue;">
                <input class="input-text animated wow flipInY delay-04s" id="id_sender" type="text" name="sender" value="Your E-mail *" onFocus="if(this.value==this.defaultValue)this.value='';" onBlur="if(this.value=='')this.value=this.defaultValue;">
                <textarea class="input-text text-area animated wow flipInY delay-06s" id="id_message" name="message" cols="0" rows="0" onFocus="if(this.value==this.defaultValue)this.value='';" onBlur="if(this.value=='')this.value=this.defaultValue;">Your Message *</textarea>
                <input class="input-btn animated wow flipInY delay-08s" type="submit" value="send message">
            </form>
          </div>
        </div>
      </div>
    </section>
  </div>
</footer>

{% endblock content %}

quest/templates/quest/results.html
{% extends "quest/base.html" %}
{% load static %}

{% block content %}

<!--Header_section-->
<div class="c-logo-part"><!--c-logo-part-start-->
  <div class="container">
      <form action="{% url 'quest:analysis' %}" method="post">
        {% csrf_token %}
        <h3 align="center">Get me some analysis on article below with {{ form }}</h3>
        <input name="url_list" type="hidden" value="{{ url_list }}" />
        <div align="center"><input class="input-btn animated wow flipInY" type="submit" value="Show me magic!" /></div>
      </form>
  </div>
</div>
<!--Top_content-->
<section id="top_content" class="top_cont_outer">
  <div class="container">
    <div class="row">
      <div class="top_left_cont flipInY wow animated">
        <h2>Articles</h2>
        <p>
          {% autoescape off %}{{ articles }}{% endautoescape %}
        </p>
      </div>
    </div>
  </div>
</section>
<!--Top_content-->

{% endblock content %}